### ISSUE TITLE
TypeError : Cannot use "in" operator to search for 'map' in undefined

### ISSUE THREAD

**Issue by legeci** [broxus/ton-locklift#35]
I'm building the tip3 token contract on Venom testnet according to the documentation found [here](https://docs.venom.foundation/build/development-guides/how-to-create-your-own-fungible-tip-3-token/quick-start-developing-with-tip-3) but every time I try to deploy I get this error message:

D:\Coded_Tale\Brand_Projects\VenomBlockchain\bread-token\node_modules\locklift\internal\factory\index.js:68
            if ("map" in map) {
                      ^
TypeError: Cannot use 'in' operator to search for 'map' in undefined
    at Factory.initializeContract (D:\Coded_Tale\Brand_Projects\VenomBlockchain\bread-token\node_modules\locklift\internal\factory\index.js:68:23)
    at D:\Coded_Tale\Brand_Projects\VenomBlockchain\bread-token\node_modules\locklift\internal\factory\index.js:154:35
    at Array.map (<anonymous>)
    at Factory.getContractsArtifacts (D:\Coded_Tale\Brand_Projects\VenomBlockchain\bread-token\node_modules\locklift\internal\factory\index.js:153:53)
    at Function.setup (D:\Coded_Tale\Brand_Projects\VenomBlockchain\bread-token\node_modules\locklift\internal\factory\index.js:126:23)
    at Function.setup (D:\Coded_Tale\Brand_Projects\VenomBlockchain\bread-token\node_modules\locklift\index.js:209:49)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at initLockliftStep (D:\Coded_Tale\Brand_Projects\VenomBlockchain\bread-token\node_modules\locklift\internal\cli\steps\initLocklift.js:8:23)
    at Command.<anonymous> (D:\Coded_Tale\Brand_Projects\VenomBlockchain\bread-token\node_modules\locklift\internal\cli\commands\run.js:38:5)

**Comment by cmstallworth** [comment]
I figured it out finally the issue is when you build your smart contract locklift doesn't build a "contractname.map.json" file as it does when you build the sample project through the init command. Since this file isn't produced during the build phase it throws the above error, I commented out the code and everything works perfectly. I don't know if this code is needed but if not you may consider removing it in future updates.
![Screenshot from 2023-12-09 00-38-15](https://github.com/broxus/locklift/assets/77358475/0d244be3-201f-4efa-b028-012aaa221b65)

**Comment by ibockowsky** [comment]
Issue still exists
